# Generated by Django 4.0.3 on 2022-04-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('moderated', 'Модерированный')], default='new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
                'db_table': 'Quotes',
            },
        ),
    ]
